export const errorTranslateMap = new Map<string, string>([
    ["auth/invalid-email", "Die eingegebene E-Mail-Adresse ist leider nicht gültig"],
    ['auth/too-many-requests', "Zu viele Anfragen. Bitte versuche es später erneut."],
    ["auth/wrong-password", "Die eingegebene E-Mail-Adresse oder das Passwort ist leider falsch"],
    ['auth/user-not-found', "Die eingegebene E-Mail-Adresse oder das Passwort ist leider falsch"],
    ["auth/popup-blocked", "Das Popup-Fenster wurde blockiert. Bitte erlauben Sie Popups für diese Seite."],
    ["auth/account-exists-with-different-credential", "SSO nicht eingerichtet. Loggen Sie sich bitte mit Ihrer E-Mail-Adresse ein und verknüpfen Sie Ihr Konto."],  
    ["Domain isn't available", "E-Mail-Adressen dieser Domain können sich leider nicht registrieren"],
    ["auth/weak-password", "Das Passwort ist zu schwach, es sollte mindestens 6 Zeichen haben."],
    ["auth/email-already-in-use", "Für diese E-Mail-Adresse existiert bereits ein Konto."],
    ["User is null.", "Das Benutzerkonto ist nicht vorhanden."],
    ["1 validation error for TextAnalysisDTO\ntext\n  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)",
    "Es muss mindestens 1 Zeichen im Feld Text ausgefüllt sein."],
    ["Bad Request - Validation", "Der eingegebene Text konnte nicht validiert werden."],
    ["Bad Request", "Der eingegebene Text konnte nicht verarbeitet werden."],
    ["Internal Server Error", "Auf dem Server ist ein Fehler aufgetreten."],    
    ["Not Found - Endpoint", "Es wurde kein Endpunkt zur Anfrage gefunden."],    
    ["OpenAI Error", "OpenAI meldet einen Fehler."],    
    ["Bad Request - OpenAI Invalid-Request", "OpenAI konnte den eingegebene Text nicht verarbeiten."],
    ["Missing or insufficient permissions.", "Bei Registierung ist ein Fehler passiert."],
]);